### PR TITLE
Use Terraform v2

### PR DESCRIPTION
**Pull request by arkiaman**

### CODE REVIEW

**Comment by arkiaman** [comment]
@AdamCoulterOz We basically done the same things at the same time yesterday ^^.
We should keep some features we've mutually implemented on our sides respectively:
- terraform sdk v2
- refactor provider config
- client => go-azure-helpers (for better auth method handling)
- WaitForState

**Comment by AdamCoulterOz** [comment]
Quoted @arkiaconsulting:
> @AdamCoulterOz We basically done the same things at the same time yesterday ^^.
> We should keep some features we've mutually implemented on our sides respectively:
> 
> * terraform sdk v2
> * refactor provider config
> * client => go-azure-helpers (for better auth method handling)
> * WaitForState

That's hilarious... well, at least we know we independently agree with each other?

@arkiaconsulting  - I've created a new PR to this PR by rebasing my changes on your new branch. Let me know what you think.

**Comment by arkiaman** [comment]
Quoted @AdamCoulterOz
> That's hilarious... well, at least we know we independently agree with each other?

Telepathy knows no frontier nor distance 😄

**Comment by arkiaman** [comment]
Resolves #16

**Pull request merged**
